on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*"
      - "script/*"
      - "patches/*"
  workflow_dispatch:
    inputs:
      skip_release:
        description: 'Skip release related steps? (true/false)'
        required: true
        default: 'false'

env:
  version: m116-d2c211228d

jobs:

  android:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        machine: [arm, arm64, x64, x86]
    steps:
      - uses: actions/checkout@v4
      - run: python3 script/check_release.py --version ${{ env.version }} --system android --machine ${{ matrix.machine }}
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
      - uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - run: sudo ./script/prepare_linux.sh
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/checkout.py --version ${{ env.version }} --system android --machine ${{ matrix.machine }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/build.py --system android --machine ${{ matrix.machine }} --ndk "/usr/local/lib/android/sdk/ndk-bundle"
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/archive.py --system android --machine ${{ matrix.machine }}
      - uses: actions/upload-artifact@v4
        with:
          name: Skia-${{ env.version }}-android-Release-${{ matrix.machine }}.zip
          path: '*.zip'
      - run: python3 script/release.py --system android --machine ${{ matrix.machine }}
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
